// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Roslynator", "RCS1032:Remove redundant parentheses.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Core.ScanSetCollection.GetScanSet(System.Int32)~DeconTools.Backend.Core.ScanSet")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.ProcessingTasks.HornDeconvolutor.FindTransform(DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.PeakProcessing.PeakData,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.PeakProcessing.ThrashV1Peak@,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.HornTransformResults@,System.Double)~System.Boolean")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.ProcessingTasks.HornDeconvolutor.PerformTransform(System.Single,System.Single,System.Int32,System.Single[]@,System.Single[]@,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.PeakProcessing.ThrashV1Peak[]@,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.HornTransformResults[]@,System.Boolean@)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.ProcessingTasks.HornDeconvolutor.SetIsotopeDistributionToZero(DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.PeakProcessing.PeakData,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.PeakProcessing.ThrashV1Peak,System.Double,System.Double,System.Double,System.Int32,System.Boolean,DeconTools.Backend.ProcessingTasks.Deconvoluters.HornDeconvolutor.ThrashV1.HornTransformResults,System.Boolean)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.Apodize(DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryApodizationType,System.Int32,System.Double,System.Int32,System.Double[]@)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.CalculateFrequencies(System.Int32,System.Int32,System.Double[]@)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.FourierTransform(System.Int32,System.Double[]@,System.Int32)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.GetIsotopePattern(System.String,System.Int32)~DeconTools.Backend.Core.IsotopicProfile")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.GetRealAndImagValues(System.Double,System.Double@,System.Double@,System.Int32)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary.", Justification = "Leave as-is", Scope = "member", Target = "~M:DeconTools.Backend.Utilities.IsotopeDistributionCalculation.MercuryIsotopicDistribution.MercuryIsoDistCreator2.Realft(System.Double[]@)~System.Int32")]
