# Jekyll configuration
name: DeconTools
description: Used to de-isotope mass spectra and to detect features from mass spectrometry data using observed isotopic signatures.
url: https://pnnl-comp-mass-spec.github.io/DeconTools/

# Google Analytics
google_analytics: G-LXXKP1N66C
